name: Deploy Go Web App to AWS EC2

on:
  push:
    branches:
      - main  # Trigger deployment on the main branch

jobs:
  deploy:
    runs-on: self-hosted  # ✅ Use the EC2 instance as the GitHub Actions runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'  # ✅ Ensure correct Go version

      - name: Build Go Application
        run: |
          go build -o go-web-app main.go
          chmod +x go-web-app  # ✅ Ensure executable permissions

      - name: Move Go Binary to Correct Location
        run: |
          sudo mv go-web-app /usr/local/bin/go-web-app
          sudo chmod +x /usr/local/bin/go-web-app

      - name: Configure Systemd Service
        run: |
          echo "✅ Creating systemd service..."
          echo "[Unit]
          Description=Go Web Application
          After=network.target

          [Service]
          ExecStart=/usr/local/bin/go-web-app -host 0.0.0.0 -port 8080
          Restart=always
          User=ec2-user
          WorkingDirectory=/home/ec2-user
          Environment=PORT=8080
          StandardOutput=journal
          StandardError=journal

          [Install]
          WantedBy=multi-user.target" | sudo tee /etc/systemd/system/go-web-app.service

          echo "✅ Reloading systemd..."
          sudo systemctl daemon-reload
          sudo systemctl enable go-web-app

      - name: Restart and Verify Service
        run: |
          echo "✅ Restarting Go Web App Service..."
          sudo systemctl restart go-web-app

          echo "✅ Checking service logs..."
          sudo systemctl status go-web-app --no-pager || sudo journalctl -xe --no-pager
